"""NPHCDA routine immunization schedule used by CNITS.

The entries in this module are transcribed from the NPHCDA immunization
schedule PDF supplied for the CNITS project.

This file contains SOURCE DATA only. Date/status calculations live in
vaccine_tracker.py so the schedule can be changed independently of the logic.
"""

VACCINE_SCHEDULE = [
    # At birth
    {
        "id": "bcg_birth",
        "series": "BCG",
        "dose_number": 1,
        "target_age_label": "At birth",
        "age_unit": "days",
        "age_value": 0,
        "vaccine": "BCG",
        "dosage": "0.05 ml",
        "route": "Intra dermal",
        "site": "Left upper arm",
    },
    {
        "id": "opv0_birth",
        "series": "OPV",
        "dose_number": 0,
        "target_age_label": "At birth",
        "age_unit": "days",
        "age_value": 0,
        "vaccine": "OPV 0",
        "dosage": "2 drops",
        "route": "Oral",
        "site": "Mouth",
    },
    {
        "id": "hep_b0_birth",
        "series": "Hep B",
        "dose_number": 0,
        "target_age_label": "At birth",
        "age_unit": "days",
        "age_value": 0,
        "vaccine": "Hep B0 birth",
        "dosage": "0.5 ml",
        "route": "Intramuscular",
        "site": "Anterolateral aspect of right thigh",
    },

    # 6 weeks
    {
        "id": "pentavalent1_6w",
        "series": "Pentavalent",
        "dose_number": 1,
        "target_age_label": "6 weeks",
        "age_unit": "weeks",
        "age_value": 6,
        "vaccine": "Pentavalent (DPT, Hep B and Hib) 1",
        "dosage": "0.5 ml",
        "route": "Intramuscular",
        "site": "Anterolateral aspect of left thigh",
    },
    {
        "id": "pcv1_6w",
        "series": "PCV",
        "dose_number": 1,
        "target_age_label": "6 weeks",
        "age_unit": "weeks",
        "age_value": 6,
        "vaccine": "Pneumococcal Conjugate Vaccine 1",
        "dosage": "0.5 ml",
        "route": "Intramuscular",
        "site": "Anterolateral aspect of right thigh",
    },
    {
        "id": "opv1_6w",
        "series": "OPV",
        "dose_number": 1,
        "target_age_label": "6 weeks",
        "age_unit": "weeks",
        "age_value": 6,
        "vaccine": "OPV 1",
        "dosage": "2 drops",
        "route": "Oral",
        "site": "Mouth",
    },
    {
        "id": "rota1_6w",
        "series": "Rota",
        "dose_number": 1,
        "target_age_label": "6 weeks",
        "age_unit": "weeks",
        "age_value": 6,
        "vaccine": "Rota 1",
        "dosage": "5 drops",
        "route": "Oral",
        "site": "Mouth",
    },
    {
        "id": "ipv1_6w",
        "series": "IPV",
        "dose_number": 1,
        "target_age_label": "6 weeks",
        "age_unit": "weeks",
        "age_value": 6,
        "vaccine": "IPV 1",
        "dosage": "0.5 ml",
        "route": "Intramuscular",
        "site": "Anterolateral aspect of right thigh (2.5cm apart from PCV)",
    },

    # 10 weeks
    {
        "id": "pentavalent2_10w",
        "series": "Pentavalent",
        "dose_number": 2,
        "target_age_label": "10 weeks",
        "age_unit": "weeks",
        "age_value": 10,
        "vaccine": "Pentavalent (DPT, Hep B and Hib) 2",
        "dosage": "0.5 ml",
        "route": "Intramuscular",
        "site": "Anterolateral aspect of left thigh",
    },
    {
        "id": "pcv2_10w",
        "series": "PCV",
        "dose_number": 2,
        "target_age_label": "10 weeks",
        "age_unit": "weeks",
        "age_value": 10,
        "vaccine": "Pneumococcal Conjugate Vaccine 2",
        "dosage": "0.5 ml",
        "route": "Intramuscular",
        "site": "Anterolateral aspect of right thigh",
    },
    {
        "id": "opv2_10w",
        "series": "OPV",
        "dose_number": 2,
        "target_age_label": "10 weeks",
        "age_unit": "weeks",
        "age_value": 10,
        "vaccine": "OPV 2",
        "dosage": "2 drops",
        "route": "Oral",
        "site": "Mouth",
    },
    {
        "id": "rota2_10w",
        "series": "Rota",
        "dose_number": 2,
        "target_age_label": "10 weeks",
        "age_unit": "weeks",
        "age_value": 10,
        "vaccine": "Rota 2",
        "dosage": "5 drops",
        "route": "Oral",
        "site": "Mouth",
    },

    # 14 weeks
    {
        "id": "pentavalent3_14w",
        "series": "Pentavalent",
        "dose_number": 3,
        "target_age_label": "14 weeks",
        "age_unit": "weeks",
        "age_value": 14,
        "vaccine": "Pentavalent 3 (DPT, Hep B and Hib)",
        "dosage": "0.5 ml",
        "route": "Intramuscular",
        "site": "Anterolateral aspect of left thigh",
    },
    {
        "id": "pcv3_14w",
        "series": "PCV",
        "dose_number": 3,
        "target_age_label": "14 weeks",
        "age_unit": "weeks",
        "age_value": 14,
        "vaccine": "Pneumococcal Conjugate Vaccine 3",
        "dosage": "0.5 ml",
        "route": "Intramuscular",
        "site": "Anterolateral aspect of right thigh",
    },
    {
        "id": "opv3_14w",
        "series": "OPV",
        "dose_number": 3,
        "target_age_label": "14 weeks",
        "age_unit": "weeks",
        "age_value": 14,
        "vaccine": "OPV 3",
        "dosage": "2 drops",
        "route": "Oral",
        "site": "Mouth",
    },
    {
        "id": "rota3_14w",
        "series": "Rota",
        "dose_number": 3,
        "target_age_label": "14 weeks",
        "age_unit": "weeks",
        "age_value": 14,
        "vaccine": "Rota 3",
        "dosage": "5 drops",
        "route": "Oral",
        "site": "Mouth",
    },
    {
        "id": "ipv2_14w",
        "series": "IPV",
        "dose_number": 2,
        "target_age_label": "14 weeks",
        "age_unit": "weeks",
        "age_value": 14,
        "vaccine": "IPV 2",
        "dosage": "0.5 ml",
        "route": "Intramuscular",
        "site": "Anterolateral aspect of right thigh (2.5cm apart from PCV)",
    },

    # 6 months
    {
        "id": "vitamin_a1_6m",
        "series": "Vitamin A",
        "dose_number": 1,
        "target_age_label": "6 months",
        "age_unit": "months",
        "age_value": 6,
        "vaccine": "Vitamin A 1st dose",
        "dosage": "100,000 IU",
        "route": "Oral",
        "site": "Mouth",
    },

    # 9 months
    {
        "id": "measles1_9m",
        "series": "Measles",
        "dose_number": 1,
        "target_age_label": "9 months",
        "age_unit": "months",
        "age_value": 9,
        "vaccine": "Measles 1st dose",
        "dosage": "0.5 ml",
        "route": "Subcutaneous",
        "site": "Left upper arm",
    },
    {
        "id": "yellow_fever_9m",
        "series": "Yellow Fever",
        "dose_number": 1,
        "target_age_label": "9 months",
        "age_unit": "months",
        "age_value": 9,
        "vaccine": "Yellow Fever",
        "dosage": "0.5 ml",
        "route": "Subcutaneous",
        "site": "Right upper arm",
    },
    {
        "id": "meningitis_9m",
        "series": "Meningitis",
        "dose_number": 1,
        "target_age_label": "9 months",
        "age_unit": "months",
        "age_value": 9,
        "vaccine": "Meningitis Vaccine",
        "dosage": "0.5 ml",
        "route": "Intramuscular",
        "site": "Anterolateral aspect of left thigh",
    },

    # 12 months
    {
        "id": "vitamin_a2_12m",
        "series": "Vitamin A",
        "dose_number": 2,
        "target_age_label": "12 months",
        "age_unit": "months",
        "age_value": 12,
        "vaccine": "Vitamin A 2nd dose",
        "dosage": "200,000 IU",
        "route": "Oral",
        "site": "Mouth",
    },

    # 15 months
    {
        "id": "measles2_15m",
        "series": "Measles",
        "dose_number": 2,
        "target_age_label": "15 months",
        "age_unit": "months",
        "age_value": 15,
        "vaccine": "Measles 2nd dose (MCV2)",
        "dosage": "0.5 ml",
        "route": "Subcutaneous",
        "site": "Left upper arm",
    },
]

# HPV is a special age-window/series entry rather than a fixed milestone.
# The source states 9-13 years, 2 doses, with a 6-month interval.
HPV_SCHEDULE = {
    "series": "HPV",
    "target_age_label": "9-13 years",
    "minimum_age_years": 9,
    "maximum_age_years": 13,
    "dose_count": 2,
    "interval_months": 6,
    "dosage": "0.5 ml",
    "route": "Intramuscular",
    "site": "Deltoid muscle (upper arm)",
}
